# Generated by Django 2.0.4 on 2018-04-24 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicativo', models.CharField(max_length=30, verbose_name='Aplicativo')),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativos',
                'ordering': ['aplicativo'],
            },
        ),
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(max_length=10, verbose_name='Tipo de Combustível')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustível',
                'ordering': ['combustivel'],
            },
        ),
        migrations.CreateModel(
            name='Ganhos_Diarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('carro', models.CharField(max_length=30, verbose_name='Carro')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Consumo(Km/L)')),
                ('horas', models.TimeField(verbose_name='Horas Trabalhadas')),
                ('corridas', models.IntegerField(verbose_name='Corridas')),
                ('cancelados', models.IntegerField(verbose_name='Cancelados')),
                ('recebido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Recebido')),
                ('incentivos', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Incentivos')),
                ('incentivos_pendentes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Incentivos Pendentes')),
                ('cancelamentos', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cancelamentos')),
                ('total_recebido', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total Recebido')),
                ('km_inicial', models.IntegerField(verbose_name='Km Inicial')),
                ('km_final', models.IntegerField(verbose_name='Km Final')),
                ('km_percorrido', models.IntegerField(verbose_name='Km Percorrido')),
                ('comb_l', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Litros Comb. Gasto')),
                ('valor_comb', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Comb.')),
                ('total_gasto_comb', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total Gasto Comb.')),
                ('preventivo', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preventivo')),
                ('extras', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Extras')),
                ('descricao', models.TextField(verbose_name='Descrição dos Gastos')),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Líquido')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aplicativos', verbose_name='App')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Combustivel', verbose_name='Combustível')),
            ],
            options={
                'verbose_name': 'Ganho Diário',
                'verbose_name_plural': 'Ganhos Diários',
                'ordering': ['data'],
            },
        ),
    ]
